### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [thrisalagopu/teacozy#4]
This project was very cleanly written and it shows through the beautiful, visual side of your project.

- Accurate to design spec.
- Working nav bar.
- Utilization of indentations and whitespace.
- Addition of comments.

Grade: Exceeds expectation, wonderful job! Will look forward to seeing your capstone!

**Comment by thrisalagopu** [comment]
Thank you Joe. I am overwhelmed. I shall continue the coding practices in the future as well. Thank you again.
